In [ ]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
T = 8  # Sequence length
D = 2  # Input dimensionality
M = 3  # Hidden layer size

X = np.random.randn(1, T, D)  # 1 sample of size T x D. We can think it as a single sentence of word vectors or some other vector signal

In [ ]:
X

array([[[-0.86759788,  0.44817691],
        [-1.57981326, -0.12402025],
        [-0.49810227,  0.07832132],
        [-0.74875906,  0.87991938],
        [-1.03513476, -1.3308771 ],
        [-0.27781837, -0.58284598],
        [-1.36489798,  1.27821434],
        [-0.79758997,  0.8383544 ]]])

In [ ]:
def lstm1():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)



In [ ]:
def lstm2():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o: ", o)
  print("h: ", h)
  print("c: ", c)

In [ ]:
def gru1():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o: ", o)
  print("h: ", h)

In [ ]:
def gru2():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)

  print("o: ", o)
  print("h: ", h)

In [ ]:
print("lstm1:")
lstm1()
print("lstm2:")
lstm2()
print("gru1:")
gru1()
print("gru2:")
gru2()

lstm1:


1/1 [==============================] - 0s 417ms/step
o: [[-0.19989757 -0.27115613 -0.40757406]]
h: [[-0.19989757 -0.27115613 -0.40757406]]
c: [[-0.43639052 -0.6221388  -0.96941066]]
lstm2:
1/1 [==============================] - 1s 694ms/step
o:  [[[-0.08655925  0.11818284 -0.04291387]
  [-0.0773178   0.29644388 -0.2877244 ]
  [-0.11155789  0.2316363  -0.22630101]
  [-0.27797928  0.24164784 -0.15470032]
  [ 0.0048619   0.228338   -0.30628893]
  [ 0.06626178  0.06347234 -0.29895177]
  [-0.16867034  0.1712563  -0.30675367]
  [-0.30545485  0.22650757 -0.16295226]]]
h:  [[-0.30545485  0.22650757 -0.16295226]]
c:  [[-0.54507697  0.5418178  -0.25880367]]
gru1:
1/1 [==============================] - 1s 603ms/step
o:  [[ 0.45756215  0.2549777  -0.42668056]]
h:  [[ 0.45756215  0.2549777  -0.42668056]]
gru2:
1/1 [==============================] - 1s 597ms/step
o:  [[[-0.19373484  0.03487708 -0.21713026]
  [-0.3942749   0.1002564  -0.3936553 ]
  [-0.31831706  0.07262447 -0.39783007]
  [-0.3261702 